### ISSUE TITLE
Not installing dependencies for Python project

### ISSUE THREAD

**Issue by WilsonCazarre** [lstoll/heroku-buildpack-monorepo#15]
I'm trying to set up Heroku monorepo to [this](https://github.com/lab-quatro/aposcar) repository.

The buildpack apparently is able to detect the Procfile and the APP_ROOT.

But it's not installing the dependencies for the project, in fact, is not running any command at all.

Build log:
```
-----> Building on the Heroku-20 stack
-----> Using buildpack: https://github.com/lstoll/heroku-buildpack-monorepo
-----> Monorepo app detected
      Copied modules/kubrick to root of app successfully
-----> Discovering process types
       Procfile declares types -> release, web
-----> Compressing...
       Done: 3.5M
-----> Launching...
 !     Release command declared: this new release will not be available until the command succeeds.
       Released v11
       https://aposcar.herokuapp.com/ deployed to Heroku
```

My release command fails because of that:
```py
Traceback (most recent call last):
  File "manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

My [Procfile](https://github.com/lab-quatro/aposcar/blob/main/modules/kubrick/Procfile) is in the APP_ROOT, not the repo root itself.
```py
release: python manage.py migrate && python manage.py loaddata initial_data/*
web: gunicorn kubrick.wsgi
```

**Comment by WilsonCazarre** [comment]
Turns out the error was pretty dumb, I forgot to set the Python buildback for my app
![image](https://user-images.githubusercontent.com/46715026/121783150-7fc98680-cb83-11eb-86a4-7f673bca5564.png)
